[package]
name = "joque"
version = "0.1.0"
edition = "2024"

[dependencies]
loom = "0.7"

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }